server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: school-service
          uri: lb://school-service
          predicates:
            - Path=/schools/**
          filters:
            - JwtFilter

        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**
          filters:
            - JwtFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
